### ISSUE TITLE
Google form niet zichtbaar als je niet ingelogd bent

### ISSUE THREAD

**Issue by lesander** [moorlag/moorlag.github.io#1]
Mooi Google formulier om je PO in te leveren, maaarrrr... 

### 1: Niet ingelogd
Als je niet ingelogd bent met een Google account, zal de iframe doorsturen naar Google's login pagina. Alleen is het probleem dat deze login pagina niet in een iframe weergegeven wil worden (`X-Frame-Options: DENY`), dus dat resulteert in een groot leeg veld :cry:. 

![](https://i.imgur.com/WdqQN8x.png)

Zie voor meer deze Google discussie:
https://productforums.google.com/forum/#!topic/docs/StVq39J3lCA
En verder nog deze vraag op Stackoverflow:
http://stackoverflow.com/questions/19137919/refused-to-display-a-website-in-a-frame-because-of-its-x-frame-options

### 2: Wel ingelogd, niet op _@pierson.nl_
Als je overigens wel ingelogd bent met een Google account, maar niet op een __@pierson.nl__ account, krijg je in koeienletters voorgeschoteld dat je geen toestemming hebt om het formulier te zien, maar geen knop om te wisselen van account.. 

![](https://i.imgur.com/XQkBkZr.png)

### Een oplossing
De beste oplossing lijkt mij om gewoon een regeltje tekst toe te voegen aan het kopje _Inleveren_, waarin staat dat je ingelogd moet zijn met je __@pierson.nl__ Google account om het formulier te kunnen zien, of nog simpeler, gewoon een link naar het formulier, zodat je wel de login pagina te zien krijgt.

**Comment by moorlag** [comment]
opgelost 👍
