### ISSUE TITLE
Typo in formulier 

### ISSUE THREAD

**Issue by skillzzjesse** [moorlag/moorlag.github.io#2]
"achternaam komma achternaam"
![screenschot](http://i.imgur.com/aaiDZm1.jpg)

**Comment by skillzzjesse** [comment]
![Screenshot](http://m.imgur.com/aaiDZm1)

**Comment by lesander** [comment]
@moorlag Moeten de leerlingen nu dan `Achternaam komma voornaam` invullen, of `Voornaam komma achternaam`?

**Comment by moorlag** [comment]
opgelost :)
